INSERT INTO menu (id, name) VALUES
(1, 'Açaí'),
(2, 'Africana'),
(3, 'Alemã'),
(4, 'Árabe'),
(5, 'Argentina'),
(6, 'Bebidas'),
(7, 'Brasileira'),
(8, 'Cafeteria'),
(9, 'Carnes'),
(10, 'Casa de Sucos'),
(11, 'Chinesa'),
(12, 'Colombiana'),
(13, 'Congelados'),
(14, 'Conveniência'),
(15, 'Coreana'),
(16, 'Doces & Bolos'),
(17, 'Espanhola'),
(18, 'Francesa'),
(19, 'Frutos do Mar'),
(20, 'Indiana'),
(21, 'Italiana'),
(22, 'Japonesa'),
(23, 'Lanches'),
(24, 'Marmita'),
(25, 'Mediterrânea'),
(26, 'Mexicana'),
(27, 'Padaria'),
(28, 'Pastel'),
(29, 'Peixes'),
(30, 'Peruana'),
(31, 'Pizza'),
(32, 'Portuguesa'),
(33, 'Salgados'),
(34, 'Saudável'),
(35, 'Sorvetes'),
(36, 'Tailandesa'),
(37, 'Vegetariana');
 