#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/core/helpers.php';


use App\Console\CommandRunner;

$argv = $_SERVER['argv'];
$argc = $_SERVER['argc'];

if ($argc < 2) {
    echo "⚠️  Nenhum comando informado.\n";
    exit;
}

$command = $argv[1];
$args = array_slice($argv, 2);

CommandRunner::handle($command, $args);
