INSERT INTO `StoreCategories` (`id`, `name`, `description`) VALUES
(1, 'Açaí', NULL),
(2, 'Africana', NULL),
(3, 'Alemã', NULL),
(4, 'Árabe', NULL),
(5, 'Argentina', NULL),
(6, 'Bebidas', NULL),
(7, 'Brasileira', NULL),
(8, 'Cafeteria', NULL),
(9, 'Carnes', NULL),
(10, 'Casa de Sucos', NULL),
(11, 'Chinesa', NULL),
(12, 'Colombiana', NULL),
(13, 'Congelados', NULL),
(14, 'Conveniência', NULL),
(15, 'Coreana', NULL),
(16, 'Doces & Bolos', NULL),
(17, 'Espanhola', NULL),
(18, 'Francesa', NULL),
(19, 'Frutos do Mar', NULL),
(20, 'Indiana', NULL),
(21, 'Italiana', NULL),
(22, 'Japonesa', NULL),
(23, 'Lanches', NULL),
(24, 'Marmita', NULL),
(25, 'Mediterrânea', NULL),
(26, 'Mexicana', NULL),
(27, 'Padaria', NULL),
(28, 'Pastel', NULL),
(29, 'Peixes', NULL),
(30, 'Peruana', NULL),
(31, 'Pizza', NULL),
(32, 'Portuguesa', NULL),
(33, 'Salgados', NULL),
(34, 'Saudável', NULL),
(35, 'Sorvetes', NULL),
(36, 'Tailandesa', NULL),
(37, 'Vegetariana', NULL);